import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

/**
 * Options for `fresh-squeezy types:augment`.
 *
 * All paths are CLI-friendly defaults: the command runs in the consumer's
 * CWD, reads their `package.json`, and writes the augmentation `.d.ts`
 * next to it (or wherever they redirect with `--out`).
 */
export interface AugmentCommandOptions {
  /** Project root. Defaults to `process.cwd()`. */
  cwd?: string;
  /** Output path for the augmentation file. Defaults to `lemonsqueezy.augment.d.ts`. */
  out?: string;
  /** Suppress "no SDK detected" message and emit the generic file anyway. */
  force?: boolean;
}

/**
 * Two flavours of file we emit.
 *
 * - `with-sdk` — the consumer has `@lemonsqueezy/lemonsqueezy.js` installed.
 *   The file imports types from the SDK and intersects them with our
 *   `Latest*Fields`. Consumers reach the augmented type via
 *   `LemonSqueezyAugmented["subscription"]`.
 *
 * - `generic` — the consumer's resource types are home-rolled or come from
 *   another SDK. The file re-exports `WithLatestLemonSqueezyFields<T, R>`
 *   so consumers can wire their own base type.
 */
type Flavour = "with-sdk" | "generic";

/**
 * Generate a `.d.ts` file in the consumer's project so their existing
 * Lemon Squeezy resource types pick up fields fresh-squeezy already knows
 * about (per the changelog audit in `src/support/manifest.ts`).
 *
 * Writes a single file. Idempotent: re-running overwrites with the
 * current version, so a CI step can safely regenerate after each
 * fresh-squeezy upgrade. Returns 0 on success, 2 on I/O failure.
 */
export async function runAugmentCommand(
  options: AugmentCommandOptions = {}
): Promise<number> {
  const cwd = options.cwd ?? process.cwd();
  const outPath = resolve(cwd, options.out ?? "lemonsqueezy.augment.d.ts");

  try {
    const flavour = await detectFlavour(cwd, options.force ?? false);
    const contents = renderAugmentationFile(flavour);
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, contents, "utf8");

    process.stdout.write(`fresh-squeezy: wrote ${outPath} (${flavour}).\n`);
    if (flavour === "with-sdk") {
      process.stdout.write(
        `Use it via: import type { LemonSqueezyAugmented } from "./lemonsqueezy.augment";\n`
      );
    } else {
      process.stdout.write(
        `Use it via: import type { WithLatestLemonSqueezyFields } from "./lemonsqueezy.augment";\n`
      );
    }
    return 0;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    process.stderr.write(`fresh-squeezy: ${message}\n`);
    return 2;
  }
}

async function detectFlavour(cwd: string, force: boolean): Promise<Flavour> {
  if (force) return "generic";
  const pkgPath = resolve(cwd, "package.json");
  if (!existsSync(pkgPath)) return "generic";

  const raw = await readFile(pkgPath, "utf8");
  const pkg = JSON.parse(raw) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
    peerDependencies?: Record<string, string>;
  };

  const deps = {
    ...(pkg.dependencies ?? {}),
    ...(pkg.devDependencies ?? {}),
    ...(pkg.peerDependencies ?? {}),
  };

  return "@lemonsqueezy/lemonsqueezy.js" in deps ? "with-sdk" : "generic";
}

function renderAugmentationFile(flavour: Flavour): string {
  const header = `/**
 * Generated by \`fresh-squeezy types:augment\` — re-run after upgrading
 * fresh-squeezy to refresh the field set.
 *
 * Why this file exists: the live Lemon Squeezy API has acquired fields
 * since the SDK / hand-rolled types in this repo were last updated
 * (e.g. \`payment_processor\`, \`tax_inclusive\`, \`refunded_amount*\`,
 * \`setup_fee*\`, \`unit_price_decimal\`, checkout color options,
 * \`skip_trial\`, \`variant_quantities\`, subscription item proration
 * flags, and order item \`quantity\`). fresh-squeezy also generates a
 * broad resource map from Lemon Squeezy's object docs, so newly documented
 * attributes can flow in after \`npm run generate:api-types\`.
 *
 * To wire it in:
 *   1. Make sure your tsconfig.json's "include" covers this file (most
 *      do by default if it's in the project root or under "src").
 *   2. Import the augmented type from this file instead of the raw SDK
 *      type — see the example at the bottom of this file.
 */

`;

  if (flavour === "with-sdk") {
    return (
      header +
      `import type {
  Subscription,
  Order,
  Variant,
  Price,
} from "@lemonsqueezy/lemonsqueezy.js";
import type {
  LatestSubscriptionFields,
  LatestSubscriptionInvoiceFields,
  LatestSubscriptionItemUpdateFields,
  LatestOrderFields,
  LatestOrderItemFields,
  LatestVariantFields,
  LatestPriceFields,
  LatestCheckoutFields,
  LatestCheckoutOptionsFields,
  LatestCheckoutDataFields,
  LatestLemonSqueezyResourceName,
  LatestFieldsFor,
  WithLatestLemonSqueezyFields,
  GeneratedLemonSqueezyFieldMap,
  GeneratedLemonSqueezyResourceName,
  GeneratedLemonSqueezyResourceType,
} from "fresh-squeezy";

/**
 * One-stop reference for resources fresh-squeezy has wider knowledge of
 * than the official SDK. The shape mirrors the SDK's response envelope
 * (\`{ data: { attributes: ... } }\`) — only the inner attributes are
 * widened.
 */
export interface LemonSqueezyAugmented {
  subscription: AugmentResponse<Subscription, LatestSubscriptionFields>;
  order: AugmentResponse<Order, LatestOrderFields>;
  variant: AugmentResponse<Variant, LatestVariantFields>;
  price: AugmentResponse<Price, LatestPriceFields>;
}

export type {
  WithLatestLemonSqueezyFields,
  LatestSubscriptionFields,
  LatestSubscriptionInvoiceFields,
  LatestSubscriptionItemUpdateFields,
  LatestOrderFields,
  LatestOrderItemFields,
  LatestVariantFields,
  LatestPriceFields,
  LatestCheckoutFields,
  LatestCheckoutOptionsFields,
  LatestCheckoutDataFields,
  LatestLemonSqueezyResourceName,
  LatestFieldsFor,
  GeneratedLemonSqueezyFieldMap,
  GeneratedLemonSqueezyResourceName,
  GeneratedLemonSqueezyResourceType,
};

/**
 * Helper that walks the official SDK's response envelope and intersects
 * the inner \`attributes\` record with the supplied field set.
 */
type AugmentResponse<T, Fields> = T extends {
  data: infer Data;
}
  ? Data extends { attributes: infer Attrs }
    ? Omit<T, "data"> & {
        data: Omit<Data, "attributes"> & { attributes: Attrs & Fields };
      }
    : T
  : T;

/* Example:
 *
 * import type { LemonSqueezyAugmented } from "./lemonsqueezy.augment";
 *
 * function describe(sub: LemonSqueezyAugmented["subscription"]) {
 *   const attrs = sub.data.attributes;
 *   console.log(attrs.payment_processor); // ← typed, no manual extension
 *   console.log(attrs.urls?.update_customer_portal);
 * }
 */
`
    );
  }

  return (
    header +
    `import type {
  WithLatestLemonSqueezyFields,
  LatestSubscriptionFields,
  LatestSubscriptionInvoiceFields,
  LatestSubscriptionItemUpdateFields,
  LatestOrderFields,
  LatestOrderItemFields,
  LatestVariantFields,
  LatestPriceFields,
  LatestCheckoutFields,
  LatestCheckoutOptionsFields,
  LatestCheckoutDataFields,
  LatestLemonSqueezyResourceName,
  LatestFieldsFor,
  GeneratedLemonSqueezyFieldMap,
  GeneratedLemonSqueezyResourceName,
  GeneratedLemonSqueezyResourceType,
} from "fresh-squeezy";

export type {
  WithLatestLemonSqueezyFields,
  LatestSubscriptionFields,
  LatestSubscriptionInvoiceFields,
  LatestSubscriptionItemUpdateFields,
  LatestOrderFields,
  LatestOrderItemFields,
  LatestVariantFields,
  LatestPriceFields,
  LatestCheckoutFields,
  LatestCheckoutOptionsFields,
  LatestCheckoutDataFields,
  LatestLemonSqueezyResourceName,
  LatestFieldsFor,
  GeneratedLemonSqueezyFieldMap,
  GeneratedLemonSqueezyResourceName,
  GeneratedLemonSqueezyResourceType,
};

/* Example with a hand-rolled or third-party type:
 *
 * import type { WithLatestLemonSqueezyFields } from "./lemonsqueezy.augment";
 *
 * type MySubscription = WithLatestLemonSqueezyFields<MyExistingSubscription, "subscription">;
 *
 * function describe(sub: MySubscription) {
 *   console.log(sub.payment_processor);   // typed
 *   type MyCheckout = WithLatestLemonSqueezyFields<MyExistingCheckout, "checkout">;
 * }
 */
`
  );
}
