name: ci
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test.yml
  biome:
    uses: ./.github/workflows/biome.yml
  typecheck:
    uses: ./.github/workflows/typecheck.yml
  build:
    uses: ./.github/workflows/build.yml
  api-types:
    uses: ./.github/workflows/api-types.yml
